services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: houseprice-app:latest
    command: python src/app.py
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: houseprice-streamlit:latest
    command: streamlit run dashboard/app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    environment:
      APP_URL: http://app:8000
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    depends_on:
      - app